name: code

on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * 0'

defaults:
  run:
    shell: bash

jobs:

  test:
    name: ${{ matrix.job.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - name: Build
            command: make build
          - name: Test
            command: make test
          - name: Lint
            command: make lint
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - run: ${{ matrix.job.command }}
