name: code

on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * 0'

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Lint
      run: make lint
