name: code

on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * 0'

defaults:
  run:
    shell: bash

jobs:

  test:
    name: ${{ matrix.job.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - name: Test
            command: make test
          - name: Lint
            command: make lint
    steps:
    - uses: actions/checkout@v3.2.0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: make build

    - name: ${{ matrix.job.name }}
      run: ${{ matrix.job.command }}
